PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS groups(id INTEGER PRIMARY KEY,name TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,username TEXT UNIQUE NOT NULL,nickname TEXT UNIQUE NOT NULL,password TEXT NOT NULL,fullname TEXT NOT NULL,birthdate TEXT NOT NULL,address TEXT NOT NULL,group_id INTEGER REFERENCES groups(id),role TEXT NOT NULL DEFAULT 'member',expertise TEXT DEFAULT '');
CREATE TABLE IF NOT EXISTS settings(id INTEGER PRIMARY KEY CHECK(id=1),r REAL NOT NULL);
INSERT OR IGNORE INTO settings VALUES(1,0.5);
CREATE TABLE IF NOT EXISTS proposals(id INTEGER PRIMARY KEY,author INTEGER REFERENCES users(id),kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT NOT NULL,category TEXT NOT NULL,tags TEXT NOT NULL,group_ids TEXT NOT NULL,target INTEGER,parent INTEGER,status TEXT NOT NULL DEFAULT 'draft',deadline REAL,r REAL,restrictive INTEGER DEFAULT 0,effect TEXT DEFAULT 'learning',review TEXT,reviewer INTEGER REFERENCES users(id),decision TEXT,applied INTEGER DEFAULT 0,created REAL NOT NULL);
CREATE TABLE IF NOT EXISTS electorate(proposal_id INTEGER REFERENCES proposals(id),user_id INTEGER REFERENCES users(id),group_id INTEGER REFERENCES groups(id),PRIMARY KEY(proposal_id,user_id));
CREATE TABLE IF NOT EXISTS votes(proposal_id INTEGER REFERENCES proposals(id),user_id INTEGER REFERENCES users(id),choice TEXT CHECK(choice IN ('accept','reject','abstain')),reason TEXT NOT NULL,PRIMARY KEY(proposal_id,user_id),FOREIGN KEY(proposal_id,user_id) REFERENCES electorate(proposal_id,user_id));
CREATE TABLE IF NOT EXISTS topics(id INTEGER PRIMARY KEY,title TEXT NOT NULL,body TEXT NOT NULL,category TEXT NOT NULL,group_ids TEXT NOT NULL,parent INTEGER REFERENCES topics(id),proposal_id INTEGER REFERENCES proposals(id));
CREATE TABLE IF NOT EXISTS topic_versions(id INTEGER PRIMARY KEY,topic_id INTEGER REFERENCES topics(id),proposal_id INTEGER REFERENCES proposals(id),title TEXT,body TEXT,created REAL);
CREATE TABLE IF NOT EXISTS messages(id INTEGER PRIMARY KEY,topic_id INTEGER REFERENCES topics(id),author INTEGER REFERENCES users(id),kind TEXT NOT NULL,body TEXT NOT NULL,url TEXT,reply_to INTEGER REFERENCES messages(id),hidden INTEGER DEFAULT 0,hidden_reason TEXT,created REAL NOT NULL,edited REAL);
CREATE TABLE IF NOT EXISTS message_versions(id INTEGER PRIMARY KEY,message_id INTEGER REFERENCES messages(id),body TEXT NOT NULL,created REAL);
CREATE TABLE IF NOT EXISTS helpful(message_id INTEGER REFERENCES messages(id),user_id INTEGER REFERENCES users(id),PRIMARY KEY(message_id,user_id));
CREATE TABLE IF NOT EXISTS points(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),source TEXT UNIQUE NOT NULL,reason TEXT NOT NULL,amount INTEGER NOT NULL,created REAL NOT NULL);
CREATE TABLE IF NOT EXISTS appeals(id INTEGER PRIMARY KEY,proposal_id INTEGER REFERENCES proposals(id),author INTEGER REFERENCES users(id),body TEXT NOT NULL,response TEXT,status TEXT DEFAULT 'open',created REAL);
CREATE TABLE IF NOT EXISTS opinions(id INTEGER PRIMARY KEY,topic_id INTEGER REFERENCES topics(id),expert INTEGER REFERENCES users(id),body TEXT NOT NULL,conflict TEXT NOT NULL,created REAL);
CREATE TABLE IF NOT EXISTS expert_requests(id INTEGER PRIMARY KEY,topic_id INTEGER REFERENCES topics(id),author INTEGER REFERENCES users(id),body TEXT,created REAL);
CREATE TABLE IF NOT EXISTS notifications(id INTEGER PRIMARY KEY,user_id INTEGER REFERENCES users(id),body TEXT,link TEXT,created REAL);
CREATE TABLE IF NOT EXISTS events(id INTEGER PRIMARY KEY,kind TEXT NOT NULL,object_id INTEGER NOT NULL,stamp REAL NOT NULL,previous TEXT NOT NULL,digest TEXT NOT NULL);
CREATE TRIGGER IF NOT EXISTS events_no_update BEFORE UPDATE ON events BEGIN SELECT RAISE(ABORT,'append-only'); END;
CREATE TRIGGER IF NOT EXISTS events_no_delete BEFORE DELETE ON events BEGIN SELECT RAISE(ABORT,'append-only'); END;
CREATE TABLE IF NOT EXISTS policy_changes(id INTEGER PRIMARY KEY,author INTEGER REFERENCES users(id),r REAL,reason TEXT,approved_by INTEGER REFERENCES users(id),created REAL);
CREATE TABLE IF NOT EXISTS follows(user_id INTEGER REFERENCES users(id),topic_id INTEGER REFERENCES topics(id),PRIMARY KEY(user_id,topic_id));
